


const carDatabase = [
    {
        name: "Acura ZDX",
        description: "Electric Family-Sized SUV",
        price: "Starting at $64,500",
        range: "278 miles",
        price_score: 3,
        style_score: 2,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "Audi e-tron GT",
        description: "Electic Sports Car",
        price: "Starting at $106,500",
        range: "249 miles",
        price_score: 5,
        style_score: 5,
        range_score: 3,
        mileage_score: 3,
        size_score: 2,
        seats_score: 4,
        family_score: 2,
        usage_score: 2,
        speed_score: 5,
        performance_score: 5
    },
    {
        name: "Audi Q4 e-tron ",
        description: "Electric SUV",
        price: "Starting at $49,800",
        range: "265 miles",
        price_score: 2,
        style_score: 2,
        range_score: 2,
        mileage_score: 2,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Audi Q4 Sportback e-tron",
        description: "Electric SUV",
        price: "Starting at $58,200",
        range: "242 miles",
        price_score: 3,
        style_score: 2,
        range_score: 1,
        mileage_score: 1,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Audi Q5 PHEV",
        description: "Electric SUV",
        price: "Starting at $57,800",
        range: "362 miles ",
        price_score: 3,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Audi Q6 e-tron",
        description: "Electric SUV",
        price: "Starting at $66,800",
        range: "307 miles",
        price_score: 3,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 4,
        performance_score: 5
    },
    {
        name: "Audi Q8 e-tron",
        description: "Electric SUV",
        price: "Starting at $74,000",
        range: "285 miles",
        price_score: 3,
        style_score: 3,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 5,
        family_score: 2,
        usage_score: 3,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Audi Q8 Sportback e-tron",
        description: "Eectric SUV",
        price: "Starting at $77,800",
        range: "300 miles",
        price_score: 4,
        style_score: 3,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 5,
        family_score: 2,
        usage_score: 3,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Audi SQ6 e-tron",
        description: "Electric SUV",
        price: "Starting at $80,800",
        range: "276 miles",
        price_score: 4,
        style_score: 2,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 4,
        performance_score: 5
    },
    {
        name: "Audi SQ8 e-tron",
        description: "Electric SUV",
        price: "Starting at $89,000",
        range: "253 miles",
        price_score: 4,
        style_score: 2,
        range_score: 2,
        mileage_score: 2,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Audi SQ8 Sportback e-tron",
        description: "Electric SUV",
        price: "Starting at $92,600",
        range: "253 miles",
        price_score: 4,
        style_score: 2,
        range_score: 2,
        mileage_score: 2,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "BMW i4",
        description: "Electric Sedan",
        price: "Starting at $52,000",
        range: "301 miles",
        price_score: 3,
        style_score: 4,
        range_score: 4,
        mileage_score: 4,
        size_score: 3,
        seats_score: 5,
        family_score: 3,
        usage_score: 3,
        speed_score: 4,
        performance_score: 4
    },
    {
        name: "BMW i5",
        description: "Electric SUV",
        price: "Starting at $67,100",
        range: "239 miles",
        price_score: 3,
        style_score: 2,
        range_score: 1,
        mileage_score: 1,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "BMX i7",
        description: "Electric SUV",
        price: "Starting at $105,700",
        range: "268 miles",
        price_score: 5,
        style_score: 2,
        range_score: 2,
        mileage_score: 2,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "BMX iX",
        description: "Electric SUV",
        price: "Starting at $75,150",
        range: "279 miles",
        price_score: 4,
        style_score: 2,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "Cadillac Celestiq",
        description: "Electric Sedan",
        price: "Starting at $300,000",
        range: "303 miles",
        price_score: 5,
        style_score: 3,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 5,
        family_score: 2,
        usage_score: 3,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Cadillac Escalade IQ",
        description: "Electric SUV",
        price: "Starting at $127,700",
        range: "450 miles",
        price_score: 5,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "Cadillac Lyriq",
        description: "Electric SUV",
        price: "Starting at $58,595",
        range: "314 miles",
        price_score: 3,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Chevrolet Blazer EV",
        description: "Electric SUV",
        price: "Starting at $44,600",
        range: "283 miles",
        price_score: 2,
        style_score: 2,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Chevrolet Equinox EV",
        description: "Electric SUV",
        price: "Starting at $33,600",
        range: "319 miles",
        price_score: 2,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "Chevrolet Silverado EV",
        description: "Electric Truck",
        price: "Starting at $55,000",
        range: "390 miles",
        price_score: 3,
        style_score: 3,
        range_score: 4,
        mileage_score: 4,
        size_score: 3,
        seats_score: 5,
        family_score: 2,
        usage_score: 5,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "Dodge Charger Daytona",
        description: "Electric Sports Car",
        price: "Starting at $57,995",
        range: "241 miles",
        price_score: 3,
        style_score: 3,
        range_score: 1,
        mileage_score: 1,
        size_score: 4,
        seats_score: 5,
        family_score: 2,
        usage_score: 3,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Fiat 500e",
        description: "Electric Hatchback",
        price: "Starting at $32,500",
        range: "180 miles",
        price_score: 2,
        style_score: 1,
        range_score: 0,
        mileage_score: 0,
        size_score: 1,
        seats_score: 2,
        family_score: 0,
        usage_score: 0,
        speed_score: 4,
        performance_score: 5
    },
    {
        name: "Ford E-Transit",
        description: "Electric Van",
        price: "Starting at $45,700",
        range: "126 miles",
        price_score: 2,
        style_score: 1,
        range_score: 0,
        mileage_score: 0,
        size_score: 5,
        seats_score: 8,
        family_score: 4,
        usage_score: 5,
        speed_score: 4,
        performance_score: 5
    },
    {
        name: "Ford F-150 Lightning",
        description: "Electric Truck",
        price: "Starting at $49,995",
        range: "320 miles",
        price_score: 3,
        style_score: 3,
        range_score: 4,
        mileage_score: 3,
        size_score: 5,
        seats_score: 5,
        family_score: 4,
        usage_score: 5,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Ford Mustang Mach-E",
        description: "Electric SUV",
        price: "Starting at $39,495",
        range: "320 miles",
        price_score: 2,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "Genesis Electric G80",
        description: "Electric Sedan",
        price: "Starting at $74,375",
        range: "282 miles",
        price_score: 3,
        style_score: 3,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 5,
        family_score: 2,
        usage_score: 3,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Genesis Electric GV70",
        description: "Electric SUV",
        price: "Starting at $66,950",
        range: "236 miles",
        price_score: 3,
        style_score: 2,
        range_score: 1,
        mileage_score: 1,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Genesis GV60",
        description: "Electric SUV",
        price: "Starting at $52,350",
        range: "294 miles",
        price_score: 3,
        style_score: 2,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "GMC Hummer EV Pickup",
        description: "Electric Truck",
        price: "Starting at $96,550",
        range: "312 miles",
        price_score: 4,
        style_score: 3,
        range_score: 4,
        mileage_score: 4,
        size_score: 3,
        seats_score: 4,
        family_score: 1,
        usage_score: 0,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "GMC Hummer EV Suv",
        description: "Electric SUV",
        price: "Starting at $96,550",
        range: "312 miles",
        price_score: 4,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "GMC Sierra EV",
        description: "Electric Truck",
        price: "Starting at $89,900",
        range: "390 miles",
        price_score: 4,
        style_score: 3,
        range_score: 4,
        mileage_score: 4,
        size_score: 3,
        seats_score: 5,
        family_score: 2,
        usage_score: 5,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Honda Prologue",
        description: "Electric SUV",
        price: "Starting at $47,400",
        range: "273 miles",
        price_score: 2,
        style_score: 2,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Hyundai  KONA Electric",
        description: "Electric SUV",
        price: "Starting at $31,975",
        range: "258 miles",
        price_score: 2,
        style_score: 2,
        range_score: 2,
        mileage_score: 2,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Hyundai IONIQ 5",
        description: "Electric Crossover",
        price: "Starting at $41,450",
        range: "303 miles",
        price_score: 2,
        style_score: 4,
        range_score: 4,
        mileage_score: 4,
        size_score: 3,
        seats_score: 5,
        family_score: 4,
        usage_score: 4,
        speed_score: 3,
        performance_score: 3
    },
    {
        name: "Hyundai IONIQ 5 N",
        description: "Electric SUV",
        price: "Starting at $66,200",
        range: "221 miles",
        price_score: 3,
        style_score: 2,
        range_score: 0,
        mileage_score: 0,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Hyundai IONIQ 6",
        description: "Electric Sedan",
        price: "Starting at $37,850",
        range: "361 miles",
        price_score: 2,
        style_score: 3,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 5,
        family_score: 2,
        usage_score: 3,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "Hyundai NEXO Fuel Cell",
        description: "Electric SUV",
        price: "Starting at $60,135",
        range: "380 miles",
        price_score: 3,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Jeep Wagonneer S",
        description: "Electric SUV",
        price: "Starting at $65,200",
        range: "270 miles",
        price_score: 3,
        style_score: 2,
        range_score: 2,
        mileage_score: 2,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "KIA EV6",
        description: "Electric Crossover",
        price: "Starting at $42,600",
        range: "310 miles",
        price_score: 2,
        style_score: 4,
        range_score: 4,
        mileage_score: 4,
        size_score: 3,
        seats_score: 5,
        family_score: 4,
        usage_score: 4,
        speed_score: 3,
        performance_score: 3
    },
    {
        name: "KIA EV9",
        description: "Electric SUV",
        price: "Starting at $54,900",
        range: "305 miles",
        price_score: 3,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "KIA Niro",
        description: "Electric SUV",
        price: "Starting at $26,990",
        range: "253 miles",
        price_score: 1,
        style_score: 2,
        range_score: 2,
        mileage_score: 2,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Lexus RZ",
        description: "Electric SUV",
        price: "Starting at $42,800",
        range: "220 miles",
        price_score: 2,
        style_score: 2,
        range_score: 0,
        mileage_score: 0,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Lucid Air",
        description: "Electric Sedan",
        price: "Starting at $87,400",
        range: "516 miles",
        price_score: 4,
        style_score: 5,
        range_score: 5,
        mileage_score: 5,
        size_score: 3,
        seats_score: 5,
        family_score: 3,
        usage_score: 3,
        speed_score: 5,
        performance_score: 5
    },
    {
        name: "Lucid Gravity",
        description: "Electric SUV",
        price: "Starting at $94,900",
        range: "450 miles",
        price_score: 4,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "Maserati GranCabrio Folgore",
        description: "Electric Convertible",
        price: "Starting at $184,000",
        range: "250 miles",
        price_score: 5,
        style_score: 5,
        range_score: 1,
        mileage_score: 1,
        size_score: 2,
        seats_score: 2,
        family_score: 0,
        usage_score: 0,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "Maserati GranTurismo Folgore",
        description: "Electric SUV",
        price: "Starting at $174,000",
        range: "300 miles",
        price_score: 5,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "Maserati Grecale Folgore",
        description: "Electric SUV",
        price: "Starting at $78,000",
        range: "200 miles",
        price_score: 4,
        style_score: 2,
        range_score: 0,
        mileage_score: 0,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 4,
        performance_score: 5
    },
    {
        name: "Mercedes EQB SUV",
        description: "Electric SUV",
        price: "Starting at $53,050",
        range: "250 miles",
        price_score: 3,
        style_score: 2,
        range_score: 1,
        mileage_score: 1,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Mercedes EQE Sedan",
        description: "Electric Sedan",
        price: "Starting at $74,900",
        range: "308 miles",
        price_score: 3,
        style_score: 3,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 5,
        family_score: 2,
        usage_score: 3,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Mercedes EQE SUV",
        description: "Electric SUV",
        price: "Starting at $77,900",
        range: "302 miles",
        price_score: 4,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Mercedes EQS Sedan",
        description: "Electric Sedan",
        price: "Starting at $104,400",
        range: "350 miles",
        price_score: 5,
        style_score: 5,
        range_score: 4,
        mileage_score: 4,
        size_score: 3,
        seats_score: 5,
        family_score: 3,
        usage_score: 3,
        speed_score: 4,
        performance_score: 5
    },
    {
        name: "Mercedes EQS SUV",
        description: "Electric SUV",
        price: "Starting at $105,250",
        range: "323 miles",
        price_score: 5,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Mercedes G-Class SUV",
        description: "Electric SUV",
        price: "Starting at $148,250",
        range: "379 miles",
        price_score: 5,
        style_score: 4,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 4,
        family_score: 1,
        usage_score: 0,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Mercedes Maybach EQS SUV",
        description: "Electric SUV",
        price: "Starting at $179,900",
        range: "280 miles",
        price_score: 5,
        style_score: 2,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Mini Countryman Electric",
        description: "Electric SUV",
        price: "Starting at $39,000",
        range: "270 miles",
        price_score: 2,
        style_score: 2,
        range_score: 2,
        mileage_score: 2,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Nissan ARIYA",
        description: "Electric SUV",
        price: "Starting at $39,770",
        range: "289 miles",
        price_score: 2,
        style_score: 2,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "Nissan Leaf",
        description: "Electric SUV",
        price: "Starting at $28,040",
        range: "212 miles",
        price_score: 1,
        style_score: 2,
        range_score: 2,
        mileage_score: 4,
        size_score: 2,
        seats_score: 5,
        family_score: 3,
        usage_score: 4,
        speed_score: 2,
        performance_score: 2
    },
    {
        name: "Polestar 2",
        description: "Electric SUV",
        price: "Starting at $49,800",
        range: "270 miles",
        price_score: 3,
        style_score: 4,
        range_score: 3,
        mileage_score: 4,
        size_score: 3,
        seats_score: 5,
        family_score: 3,
        usage_score: 3,
        speed_score: 4,
        performance_score: 4
    },
    {
        name: "Polestar 3",
        description: "Electric SUV",
        price: "Starting at $60,000",
        range: "300 miles",
        price_score: 3,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Porsche Cross Tursimo",
        description: "Electric Wagon",
        price: "Starting at $92,000",
        range: "300 miles",
        price_score: 4,
        style_score: 5,
        range_score: 4,
        mileage_score: 4,
        size_score: 5,
        seats_score: 8,
        family_score: 4,
        usage_score: 5,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Porsche Macan EV",
        description: "Electric SUV",
        price: "Starting at $59,000",
        range: "263 miles",
        price_score: 3,
        style_score: 2,
        range_score: 2,
        mileage_score: 2,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Porsche Taycan",
        description: "Electric Sports Car",
        price: "Starting at $86,700",
        range: "246 miles",
        price_score: 4,
        style_score: 5,
        range_score: 3,
        mileage_score: 3,
        size_score: 2,
        seats_score: 4,
        family_score: 2,
        usage_score: 2,
        speed_score: 5,
        performance_score: 5
    },
    {
        name: "Ram ProMaster EV",
        description: "Electric Van",
        price: "Starting at $52,000",
        range: "150 miles",
        price_score: 3,
        style_score: 1,
        range_score: 0,
        mileage_score: 0,
        size_score: 5,
        seats_score: 8,
        family_score: 4,
        usage_score: 5,
        speed_score: 4,
        performance_score: 5
    },
    {
        name: "Rivian R1S",
        description: "Electric SUV",
        price: "Starting at $78,000",
        range: "316 miles",
        price_score: 4,
        style_score: 4,
        range_score: 4,
        mileage_score: 3,
        size_score: 5,
        seats_score: 7,
        family_score: 5,
        usage_score: 5,
        speed_score: 4,
        performance_score: 4
    },
    {
        name: "Rivian R1T",
        description: "Electric Truck",
        price: "Starting at $69,900",
        range: "270 miles",
        price_score: 3,
        style_score: 3,
        range_score: 2,
        mileage_score: 2,
        size_score: 3,
        seats_score: 5,
        family_score: 2,
        usage_score: 5,
        speed_score: 1,
        performance_score: 2
    },
    {
        name: "Rolls-Royce Spectre",
        description: "Electric Coupe",
        price: "Starting at $413,000",
        range: "260 miles",
        price_score: 5,
        style_score: 5,
        range_score: 2,
        mileage_score: 2,
        size_score: 1,
        seats_score: 2,
        family_score: 0,
        usage_score: 0,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Subaru Solterra",
        description: "Electric SUV",
        price: "Starting at $44,995",
        range: "228 miles",
        price_score: 2,
        style_score: 2,
        range_score: 0,
        mileage_score: 0,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Tesla Cyberbeast",
        description: "Electric Truck",
        price: "Starting at $99,990",
        range: "320 miles",
        price_score: 4,
        style_score: 3,
        range_score: 4,
        mileage_score: 4,
        size_score: 3,
        seats_score: 5,
        family_score: 2,
        usage_score: 5,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Tesla Cybertruck",
        description: "Electric Truck",
        price: "Starting at $72,490",
        range: "325 miles",
        price_score: 3,
        style_score: 3,
        range_score: 4,
        mileage_score: 4,
        size_score: 3,
        seats_score: 5,
        family_score: 2,
        usage_score: 5,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Tesla Model 3",
        description: "Electric Sedan",
        price: "Starting at $40,240",
        range: "272 miles",
        price_score: 2,
        style_score: 4,
        range_score: 3,
        mileage_score: 4,
        size_score: 3,
        seats_score: 5,
        family_score: 3,
        usage_score: 3,
        speed_score: 4,
        performance_score: 4
    },
    {
        name: "Tesla Model 3 Performance",
        description: "Electric Sedan",
        price: "Starting at $47,490",
        range: "298 miles",
        price_score: 2,
        style_score: 3,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 5,
        family_score: 2,
        usage_score: 3,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Tesla Model S",
        description: "Electric Sedan",
        price: "Starting at $79,990",
        range: "410 miles",
        price_score: 4,
        style_score: 3,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 5,
        family_score: 2,
        usage_score: 3,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Tesla Model S Plaid",
        description: "Electric Sedan",
        price: "Starting at $94,990",
        range: "348 miles",
        price_score: 4,
        style_score: 3,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 5,
        family_score: 2,
        usage_score: 3,
        speed_score: 4,
        performance_score: 5
    },
    {
        name: "Tesla Model X",
        description: "Electric SUV",
        price: "Starting at $84,990",
        range: "329 miles",
        price_score: 4,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Tesla Model X  Plaid",
        description: "Electric SUV",
        price: "Starting at $99,990",
        range: "314 miles",
        price_score: 4,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 3,
        performance_score: 4
    },
    {
        name: "Tesla Model Y",
        description: "Electric Crossover",
        price: "Starting at $47,490",
        range: "330 miles",
        price_score: 3,
        style_score: 4,
        range_score: 4,
        mileage_score: 4,
        size_score: 3,
        seats_score: 7,
        family_score: 4,
        usage_score: 4,
        speed_score: 4,
        performance_score: 4
    },
    {
        name: "Toyota bZ4X",
        description: "Electric SUV",
        price: "Starting at $37,070",
        range: "252 miles",
        price_score: 2,
        style_score: 2,
        range_score: 2,
        mileage_score: 2,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "VinFast VF8",
        description: "Electric SUV",
        price: "Starting at $53,000",
        range: "292 miles",
        price_score: 3,
        style_score: 2,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "VinFast VF9",
        description: "Electric SUV",
        price: "Starting at $59,000",
        range: "369 miles",
        price_score: 3,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Volkswagen ID.4",
        description: "Electric SUV",
        price: "Starting at $38,995",
        range: "275 miles",
        price_score: 2,
        style_score: 3,
        range_score: 3,
        mileage_score: 4,
        size_score: 3,
        seats_score: 5,
        family_score: 4,
        usage_score: 4,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Volkswagen ID.Buzz",
        description: "Electric Van",
        price: "Starting at $59,995",
        range: "260 miles",
        price_score: 3,
        style_score: 1,
        range_score: 2,
        mileage_score: 2,
        size_score: 5,
        seats_score: 8,
        family_score: 4,
        usage_score: 5,
        speed_score: 4,
        performance_score: 5
    },
    {
        name: "Volvo C40",
        description: "Electric SUV",
        price: "Starting at $54,895",
        range: "297 miles",
        price_score: 3,
        style_score: 2,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Volvo EX30",
        description: "Electric SUV",
        price: "Starting at $46,195",
        range: "253 miles",
        price_score: 2,
        style_score: 2,
        range_score: 2,
        mileage_score: 2,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    },
    {
        name: "Volvo EX40",
        description: "Electric SUV",
        price: "Starting at $53,795",
        range: "296 miles",
        price_score: 3,
        style_score: 2,
        range_score: 3,
        mileage_score: 3,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 2,
        performance_score: 3
    },
    {
        name: "Volvo EX90 ",
        description: "Electric SUV",
        price: "Starting at $81,290",
        range: "310 miles",
        price_score: 4,
        style_score: 2,
        range_score: 4,
        mileage_score: 4,
        size_score: 4,
        seats_score: 6,
        family_score: 3,
        usage_score: 4,
        speed_score: 0,
        performance_score: 0
    }
];

export default carDatabase;




